### ISSUE TITLE
02 Use case "Create an account"

### ISSUE THREAD

**Issue by nickeynikolov** [nickeynikolov/team-Echidna-#11]
Write the following test cases for "Create an account" use case.

**Comment by yaneva** [comment]
Create an acount works as expected. Bugs were not found.
The following Manual test case scenarios were done.

1.Follow the link   ‘ Create an account’ .
Expected result: ‘ Create an account ‘ page is displayed.  
2. Enter an email in the  email address text box.
Expected result: Entered email address should be displayed
3.Enter password in the password text box(minimum 8 characters)
Expected result:  Encrypted text should be displayed. 
4.Enter the same password in the repeat password text box (minimum 8 characters).
Expected result: Encrypted text should be displayed. 
5.Click on “ Sign up “ button
Expected result:  Message :Welcome!You have signed up successfully.” Is displayed
7 .Enter  valid email and two different passwords. Press” Sign up” button.
Expected results:
Pop-up window is displayed with the following message:” Password confirmation" doesn't match New password”.
8.Enter password less than 8 characters .Repeat the same password and press the button “ Sign up”
Expected results:
Pop-up window is displayed  with the following message:” 
"New password" is too short(minimum is 8 characters)_
9. Leave all text boxes empty and press “ Sign up” button.
Expected result: “ Email can’t be blank. “ New password can’t be blank.
