### ISSUE TITLE
07 Use case "Contacts"

### ISSUE THREAD

**Issue by nickeynikolov** [nickeynikolov/team-Echidna-#16]
Write the following test cases for "Contacts" use case.

**Comment by yaneva** [comment]
Contacts works as expected. Bugs were not found.
The following  manual test case scenarios were done:

1.Select  the link “Contacts” (right pane, refer user screens in Appendix )
Expected result: “Contact info” page“ and “ Get in touch “ form are displayed
2. Fill  out  the mandatory fields with  \* symbol(name,email, subject and message ) and press “ Send button”
Expected results:
“Message sent successfully”  message is displayed 
1. Enter name, email and subject  in the mandatory fields.Do not enter a message and press” Send” button
   Expected result: The following message is displayed: “ Please, fill all required fields correctly.”
